id: P71E9EC30
initial_creation_type: input
source_metadata:
  title: Khenpo Gangshar Wangpo
  language: en
  description: 'Texts by the Dzogchen teacher Khenpo Gangshar Wangpo (mkhan po gang
    shar dbang po, 1925–1958/9), who is known especially for his role as the root
    teacher of Chögyam Trungpa:'
  volume:
    7330d5db6c44479c80fc8edb974e7f22:
      title: A Way of Settling into the Realization of Mind’s Essence
      parent: Advice
    0c8859388cd44b17888e6815b21a6ae1:
      title: A Song of Advice for Gok Zangden
      parent: Dzogchen
    b4c109164ad445758586fbff9d236a23:
      title: A Song to Introduce the Unmistaken View of the Great Perfection
      parent: Dzogchen
    f40b3c4fa4e44b9db0031bbb3b6b0f7e:
      title: 'Naturally Liberating Whatever You Meet: A Concise Instruction for Realizing
        the Nature of Mind'
      parent: Dzogchen
    c4a77bfc18294c76a594f342d42e6718:
      title: Verses to Remove Hindrances and Sustain Realization of the Nature of
        Mind
      parent: Dzogchen
    d05001b65e0e44e9be4acafdfaa77d52:
      title: 'Vomiting Gold: A Pith Instruction in the Form of Advice for the Diligent
        Practitioner, the Excellent Atsang'
      parent: Dzogchen
    75676f99cef4489a8ee4afd499758f46:
      title: 'Guru Yoga: The Consummate Blessing'
      parent: Guru Yoga
    d219748713b843c1a2748175f909c99c:
      title: 'From the Mahāmudrā Preliminary Practices: Continuous Integration with
        Ground, Path, and Fruition'
      parent: Mahāmudrā
    7012e821006442cba80dd76298b4bef4:
      title: Prayer to Pacify Military Conflict
      parent: Prayers
created_at: '2022-03-01T00:25:04.698807'
last_modified_at: '2022-03-01T00:25:04.698813'
